### ISSUE TITLE
Update composer in order to install latest package of netsuite-php

### ISSUE THREAD

**Issue by benjy8001** [netsuitephp/netsuite-laravel#10]
The requirement of this package and the netsuite-php lead to lock to the v2022.1 version.

See https://github.com/netsuitephp/netsuite-php/blob/master/composer.json

**Comment by neclimdul** [comment]
This isn't really a bug with this project. Its the requirements of the netsuitephp/netsuite-php.

After 2022.1.0 we require psr/log v1 so if you get a project requiring v2 or v3 it will exclude those newer versions.

https://github.com/netsuitephp/netsuite-php/pull/154 addresses this it just hasn't made it into a release yet.
