### ISSUE TITLE
You can do create a Rest Suite Talk.

### ISSUE THREAD

**Issue by kelvinkrisna** [netsuitephp/netsuite-laravel#4]
Maybe you can include in code call to Suite Talk in rest. 

Maybe we can work together. https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/chapter_1540391670.html

**Comment by neclimdul** [comment]
looks like they have an OpenAPI spec so it should be easy to make a library for. That said they do seem to have made it a bit more complicated then most API's documented with OpenAPI. Here's the docs:

https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1545126526.html

**Comment by jrebs** [comment]
Hi Kelvin. This project exists simply to provide a simple way to pull the the `netsuite-php` library into a laravel application with support for things like the service container, etc. Supporting restful suite talk is well outside the scope of this project and, I would say, outside the scope of the `netsuite-php` library, which exists basically as a way to more easily consume the web services toolkit that NetSuite provides for PHP.

**Comment by neclimdul** [comment]
@jrebs if you're open and my prototyping works out would you be interested in adding a different library under netsuitephp org with the rest libraries? That was kinda where I was thinking this might go but I didn't have a better place to discuss ATM.

**Comment by jrebs** [comment]
> @jrebs if you're open and my prototyping works out would you be interested in adding a different library under netsuitephp org with the rest libraries? That was kinda where I was thinking this might go but I didn't have a better place to discuss ATM.

Definitely happy to talk about that, James, if you're up for doing the work. My workload at present precludes me from any meaningful open source contributions in the foreseeable future, but having a rest library under the organization would be great.

**Comment by neclimdul** [comment]
there's never enough time in a day. yeah, I'm hoping this lines up with some day job work so otherwise I'd generally be in a similar boat :rofl: I'll let you know.
