### ISSUE TITLE
cant publish NetsuiteServiceProvider

### ISSUE THREAD

**Issue by Silviobramas** [netsuitephp/netsuite-laravel#7]
php artisan vendor:publish --provider=NetSuite\\Providers\\NetSuiteServiceProvider

ends in the message "Unable to locate publishable resources"

And if I try
`$service = app(NetSuite\NetSuiteService::class);
$response = $service->get($request);`

I get this message: Target class [App\Http\Controllers\NetSuite\NetSuiteService] does not exist. 

can you help please

**Comment by neclimdul** [comment]
> `App\Http\Controllers\NetSuite\NetSuiteService`

I assume the class you're calling `app()` in is in the namespace `App\Http\Controllers` so the class resolver is looking for  `NetSuite\NetSuiteService` in that namespace. Try `\NetSuite\NetSuiteService:class` or include the class with use and it should work as you expected.

**Comment by Silviobramas** [comment]
That works. Thanks
