### ISSUE TITLE
Argument #2 must be of type array, int given

### ISSUE THREAD

**Issue by fruitizz** [netsuitephp/netsuite-laravel#8]
Getting this error during the authentication:

```ruby
array_merge(): Argument #2 must be of type array, int given
```

Can someone help, please?
![Screenshot 2023-05-04 at 00 40 01](https://user-images.githubusercontent.com/10519310/236066266-21afdd35-9d98-4d37-b294-312db251b06c.png)

**Comment by fruitizz** [comment]
Here is my config file content:
```ruby
<?php
    // Token-based Authentication
    require 'vendor/autoload.php';

    use NetSuite\NetSuiteService;

    $config = [
        // required -------------------------------------
        "endpoint"       => env('NS_ENDPOINT'),
        "host"           => env('NS_HOST'),
        "account"        => 'XXXXXXX',
        "consumerKey"    => env('NS_CONSUMER_KEY'),
        "consumerSecret" => env('NS_CONSUMER_SECRET'),
        "token"          => env('NS_TOKEN'),
        "tokenSecret"    => env('NS_TOKEN_SECRET')
    ];

    var_dump($config);
    $service = new NetSuiteService($config);
?>
```

**Comment by jrebs** [comment]
Your configuration looks like an example config for using the `netsuite-php` package in a custom application manner. This repository is for the `netsuite-laravel` package which provides the former in a laravel-friendly manner. The README file has instructions on configuration and how you can publish the provided config file into your laravel application if you don't want to create your own.
