### ISSUE TITLE
Class "Netsuite\Classes\GetPostingTransactionSummaryRequest" not found

### ISSUE THREAD

**Issue by fruitizz** [netsuitephp/netsuite-laravel#9]
I am trying to use the `GetPostingTransactionSummaryRequest` and I am getting the error below.
```ruby
$service = app(NetSuiteService::class);
$request = new GetPostingTransactionSummaryRequest();
```
The challenge is that the `GetPostingTransactionSummaryRequest` is in the vendor NetSuite folder but not able to call it. Is there anything I may be missing? Thanks.

![Screenshot 2023-05-04 at 14 40 55](https://user-images.githubusercontent.com/10519310/236224751-218a6191-e9ba-48a2-92eb-2f3b632a67b6.png)

**Comment by jrebs** [comment]
Not related to this package, see the duplicate issue you posted in the `netsuite-php` repo.
